#! /usr/bin/env node

const path = require('path');
const bluebird = require('bluebird')
var fs = bluebird.promisifyAll(require("fs"))
const pfe = require('./index')
const program = require('commander')


program
  .version('0.0.1')
  .option('-o, --output <path>', 'Directory to put results')
  .option('-i, --input <path>', 'Directory to process')
  .option('-t, --tmp <path>', 'Directory to put temporary files')
  .option('-p, --partials <path>', "Directory to put figure directory")
  .parse(process.argv);


if ( program.input && program.output) {
  const dirpdf = path.resolve(program.input)
  const output = path.resolve(program.output)
  let tmp, directoryPartialPath
  program.tmp ?
    (tmp = path.resolve(program.tmp)) :
    (tmp = path.resolve('tmp'))
  program.partials ?
    (directoryPartialPath = path.resolve(program.partials)) :
    (directoryPartialPath = output)


      console.log(tmp)
        console.log(directoryPartialPath)
  fs.readdirAsync(dirpdf).mapSeries(function(file) {
    if (path.extname(file) === '.pdf') {
      return new pfe({
        pdfInputPath: path.resolve(dirpdf, file),
        directoryOutputPath: output,
        directoryPartialPath: directoryPartialPath,
        tmp: tmp,
        debug:true
      }).then((self) => {
        return self.exec()
      }).catch(err=>console.log(err))

    }
  })
} else {
  console.log('Input et output arguments must be assign.')
}
